### ISSUE TITLE
How to get the meta_data.pkl?

### ISSUE THREAD

**Issue by zzpustc** [StrangerZhang/SiamFC-PyTorch#10]
Hi,StrangerZhang
Thank you for your great work, I have download the ILSVRC2015, but I can not find the meta_data.pkl. Is it generated? Hope to receive your response.
@StrangerZhang

**Comment by StrangerZhang** [comment]
yes, it is generated by bin/create_dataset.py
@zzpustc

**Comment by zzpustc** [comment]
Thanks!

**Comment by zzpustc** [comment]
I got problem below when I tried to run the training code.
AttributeError: 'NoneType' object has no attribute '__buffer__'
Is there any environment requirement?
@StrangerZhang

**Comment by StrangerZhang** [comment]
Could you provide detailed error

**Comment by zzpustc** [comment]
Here is the detailed error:
Traceback (most recent call last):
  File "bin/train_siamfc.py", line 9, in <module>
    Fire(train)
  File "/home/zzp/anaconda3/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/zzp/anaconda3/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/zzp/anaconda3/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/home/zzp/ZZP/pytorch/SiamFC-PyTorch-master/siamfc/train.py", line 94, in train
    for i, data in enumerate(tqdm(trainloader)):
  File "/home/zzp/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 979, in __iter__
    for obj in iterable:
  File "/home/zzp/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/home/zzp/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/zzp/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/zzp/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/zzp/ZZP/pytorch/SiamFC-PyTorch-master/siamfc/dataset.py", line 65, in __getitem__
    exemplar_img = self.imread(exemplar_name)
  File "/home/zzp/ZZP/pytorch/SiamFC-PyTorch-master/siamfc/dataset.py", line 38, in imread
    img_buffer = np.frombuffer(img_buffer, np.uint8)
AttributeError: 'NoneType' object has no attribute '__buffer__'
@StrangerZhang

**Comment by StrangerZhang** [comment]
check your dataset path

**Comment by zzpustc** [comment]
> check your dataset path

I can guarantee that my dataset path is right, and I have tried many times on two computers , but still got the same error.

**Comment by StrangerZhang** [comment]
It seems that your lmdb not contain the keys

better to check  [dataset.py#L33](https://github.com/StrangerZhang/SiamFC-PyTorch/blob/a61a15a2a41ad3639c237924739cd3d43b1f494e/siamfc/dataset.py#L33)

check the value of the path

**Comment by zzpustc** [comment]
Hi, I have run it successfully, but I can only get 0.5438 on the OTB2015.

**Comment by StrangerZhang** [comment]
Did you evaluate 10~30epoch then choose the best one，the result should be around 0.58

**Comment by zzpustc** [comment]
Yes，I have evaluated all the models，but the best result is just 0.5536




| |
周志鹏zzp
邮箱：15001821058@163.com
|

签名由 网易邮箱大师 定制

On 01/24/2019 17:43, StrangerZhang wrote:

Did you evaluate 10~30epoch then choose the best one，the result should be around 0.58

**Comment by zzpustc** [comment]
@StrangerZhang I can not reproduce your result, in fact , I can only get 0.5640 on the OTB2013, and 0.5608 on the OTB2015, I did not change anything... Is there any different in the evaluation code? I use the eval_otb in DaSiamRPN repo https://github.com/foolwood/DaSiamRPN/tree/master/code.
