### ISSUE TITLE
if the code can't run in win ?and if it could  run without   gpu?

### ISSUE THREAD

**Issue by AstoncPou** [StrangerZhang/SiamFC-PyTorch#13]
if it wannt  run it  without   gpu,what commend should i line in

**Comment by AstoncPou** [comment]
iamfc.py --gpu-id [0] --video-dir /home/astonc/project/SiamFC-PyTorch-master/SiamFC-PyTorch/data/David --model-path home/astonc/project/SiamFC-PyTorch-master/SiamFC-PyTorch/models 
Traceback (most recent call last):
  File "bin/demo_siamfc.py", line 57, in <module>
    Fire(main)
  File "/home/astonc/.local/lib/python3.5/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/astonc/.local/lib/python3.5/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/astonc/.local/lib/python3.5/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "bin/demo_siamfc.py", line 27, in main
    tracker = SiamFCTracker(model_path, gpu_id)
  File "/home/astonc/project/SiamFC-PyTorch-master/SiamFC-PyTorch/siamfc/tracker.py", line 21, in __init__
    with torch.cuda.device(gpu_id):
  File "/home/astonc/.local/lib/python3.5/site-packages/torch/cuda/__init__.py", line 228, in __enter__
    torch._C._cuda_setDevice(self.idx)
RuntimeError: invalid argument to setDevice

**Comment by StrangerZhang** [comment]
You should change the code yourself. Running on cpu is very slow
