### ISSUE TITLE
create_dataset.py

### ISSUE THREAD

**Issue by universefall** [StrangerZhang/SiamFC-PyTorch#19]
Hi, I try to run bin/create_dataset.py, while it says:
  0%|                                                                                         | 0/4417 [00:00<?, ?it/s]multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "E:\tensorflow\SiamFC-PyTorch-master\bin\create_dataset.py", line 20, in worker
    key=lambda x:int(x.split('/')[-1].split('.')[0]))
  File "E:\tensorflow\SiamFC-PyTorch-master\bin\create_dataset.py", line 20, in <lambda>
    key=lambda x:int(x.split('/')[-1].split('.')[0]))
ValueError: invalid literal for int() with base 10: 'ILSVRC2015_VID_train_0000\\ILSVRC2015_train_00000000\\000000'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bin/create_dataset.py", line 73, in <module>
    Fire(processing)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "bin/create_dataset.py", line 65, in processing
    functools.partial(worker, output_dir), all_videos), total=len(all_videos)):
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\tqdm\_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\pool.py", line 735, in next
    raise value
ValueError: invalid literal for int() with base 10: 'ILSVRC2015_VID_train_0000\\ILSVRC2015_train_00000000\\000000'

I downloaded the ILSVRC2015_VID and set the dir. It shows again. Is it related to pytorch version? Thank you.

**Comment by universefall** [comment]
I fixed the [bin/create_dataset.py](url) line 20 and 21 to key=lambda x:int(x.split('\\')[-1].split('.')[0]))
    video_name = video_dir.split('\\')[-1]. Just for Windows
