### ISSUE TITLE
Problem of training 

### ISSUE THREAD

**Issue by universefall** [StrangerZhang/SiamFC-PyTorch#20]
I'm following your instructions to run to python bin/train_siamfc.py --gpu-id [gpu_id] --data-dir path/to/data/ILSVRC2015_VID_CURATION. But the system reported an error.
Traceback (most recent call last):
  File "bin/train_siamfc.py", line 9, in <module>
    Fire(train)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "E:\tensorflow\SiamFC-PyTorch-master\siamfc\train.py", line 62, in train
    db = lmdb.open(data_dir+'.lmdb', readonly=True, map_size=int(50e9))
lmdb.Error: E:/tensorflow/ILSVRC_VID_CURATION.lmdb: ϵͳ�Ҳ���ָ����·����
How to solve this problem?
Thank you very much

**Comment by universefall** [comment]
after running create_lmdb.py, there are two files generated: data.mdb and lock.mdb. It seems no .lmdb.

**Comment by FadedFate** [comment]
> after running create_lmdb.py, there are two files generated: data.mdb and lock.mdb. It seems no .lmdb.

I guess your problem may be caused by using a incorrect second instruction.
```
python bin/create_lmdb.py --data-dir path/to/data/ILSVRC2015_VID_CURATION \
			  --output-dir path/to/data/ILSVRC2015_VID_CURATION.lmdb \
		          --num-threads 8
```
Plz note that the output-dir should be ***.lmdb file** , not an output file-floder dir.

**Comment by FadedFate** [comment]
> after running create_lmdb.py, there are two files generated: data.mdb and lock.mdb. It seems no .lmdb.

I guess your problem may be caused by using a different output file path for the second instruction.
```
python bin/create_lmdb.py --data-dir path/to/data/ILSVRC2015_VID_CURATION \
			  --output-dir path/to/data/ILSVRC2015_VID_CURATION.lmdb \
		          --num-threads 8
```
Plz note that the output-dir should be **"*.lmdb"**  file-folder dir, maybe not another output file-floder dir (or just move the new file folder to the same path).
